### ISSUE TITLE
wx.u.getUserInfo 这里的u指的是什么

### ISSUE THREAD

**Issue by yaoshanliang** [kesixin/QuestionWechatApp#4]
如题，wx.u这里报错了，这里的u指的是啥。

![image](https://user-images.githubusercontent.com/5028569/63679841-e05bc800-c824-11e9-8be1-0aa5adc297e6.png)
![image](https://user-images.githubusercontent.com/5028569/63679900-01bcb400-c825-11e9-94de-c6965d1666f7.png)

**Comment by Totn** [comment]
@kesixin 没有给出解答，为何关闭了呢？
